import java.util.Random;

// Users are capable of basic interaction, i.e. voting, joining sessions, and leaving sessions.

public class User implements Voter {
	
	// Using int to simulate database autoincremented user_id field
	// Normally, this would be generated by the database, but I don't want to
	// Program a database at the moment
	private int ID;
	
	// This is our connection to the server. 
	private Server server; // Simulates session with server
	private IVoteService ivs; // Room that we join

	public User(int i) {
		ID = i;
	}

	// A setter method for server
	public void connectToServer(Server s) {
		server = s;
	}
	
	public void submitAnswer(Integer[] i) {
		ivs.addAnswer(ID, i);
	}
		
	public int getID() {
		return ID;
	}
	
	public void joinRoom(String token) {
		ivs = server.getRoom(token);
	}
}
